# _global/config.yml
# ==================================================
# CONFIGURACIÓN GLOBAL — Compartida entre sub-sitios
# ==================================================

# Tema
theme: just-the-docs

# Esquema de color (opciones: "light", "dark")
color_scheme: dark

# Favicon
favicon_ico: "/assets/images/favicon.ico"

# Búsqueda
search_enabled: true
search:
  heading_level: 2
  previews: 3

# Navegación
nav_enabled: true
heading_anchors: true

# External navigation links
nav_external_links:
  - title: Hablemos por Telegram
    url: https://t.me/chipaaco
    hide_icon: true # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false


aux_links:
  "Lista de todos los apuntes":
    - "https://github.com/chipaaco/apuntes?tab=readme-ov-file#sub-sitios"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Textos y Componentes Generales
back_to_top: true
back_to_top_text: "Volver arriba"

# Footer
gh_edit_link: true
gh_edit_link_text: "Editar esta página en GitHub"
gh_edit_repository: "https://github.com/chipaaco/apuntes"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

# Plugins requeridos
plugins:
  - jekyll-seo-tag

# Renderizado de LaTeX (MathJax)
math: mathjax
use_math: true
mathjax:
  tex:
    inlineMath: [['$', '$'], ['\\(', '\\)']]
    displayMath: [['$$', '$$'], ['\\[', '\\]']]
    processEscapes: true
    processEnvironments: true
  options:
    ignoreHtmlClass: 'tex2jax_ignore'
    processHtmlClass: 'tex2jax_process'
